global.VERSION = 90359;
global.WORKER_SIZE = 256;

global.LOGIN_IP = '127.0.0.1';
global.LOGIN_PO = 11091;
global.MAX_USER_FOR_LOGIN = 1000;

global.MY_HOST = '127.0.0.1';
global.MY_PORT = 3306;
global.MY_USER = 'root';
global.MY_PASS = 'dos';
global.MY_DB = '';
global.MY_TB01 = 'DefineMaxUserNum';
global.MY_TB02 = 'MemberInfo';
global.MY_TB03 = 'AvatarInfo';
global.MY_TB04 = 'MasterInfo';

global.MAX_USER_ID_LENGTH = 101;
global.MAX_USER_PASSWORD_LENGTH = 101;
global.MAX_MOUSE_PASSWORD_LENGTH = 5;

global.MAX_USER_AVATAR_NUM				=	3;
global.MAX_AVATAR_NAME_LENGTH				=	13;
global.MAX_EQUIP_SLOT_NUM = 13;
global.MAX_CALL_NAME_LENGTH				=	5;
global.MAX_STORE_ITEM_SLOT_NUM			=	28;
global.MAX_SKILL_SLOT_NUM					=	40;


global.SIZE_OF_AVATAR_INFO = 7896;
//CLIENT -> LOGIN;
global.P_LOGIN_SEND						=	11;
global.S_LOGIN_SEND						=	13 + MAX_USER_ID_LENGTH + MAX_USER_PASSWORD_LENGTH;
global.P_CLIENT_OK_FOR_LOGIN_SEND			=	12;
global.S_CLIENT_OK_FOR_LOGIN_SEND			=	9;
global.P_CREATE_MOUSE_PASSWORD_SEND		=	13;
global.S_CREATE_MOUSE_PASSWORD_SEND		=	9 + MAX_MOUSE_PASSWORD_LENGTH;
global.P_CHANGE_MOUSE_PASSWORD_SEND		=	14;
global.S_CHANGE_MOUSE_PASSWORD_SEND		=	9 + MAX_MOUSE_PASSWORD_LENGTH + MAX_MOUSE_PASSWORD_LENGTH;
global.P_LOGIN_MOUSE_PASSWORD_SEND		=	15;
global.S_LOGIN_MOUSE_PASSWORD_SEND		=	9 + MAX_MOUSE_PASSWORD_LENGTH;
global.P_CREATE_AVATAR_SEND 				=	17;
global.S_CREATE_AVATAR_SEND				=	13 + SIZE_OF_AVATAR_INFO;
global.P_DELETE_AVATAR_SEND				=	18;
global.S_DELETE_AVATAR_SEND				=	21;

//LOGIN -> CLIENT;
global.P_LOGIN_RECV						=	11;
global.S_LOGIN_RECV						=	339;
global.P_USER_AVATAR_INFO					=	12;
global.S_USER_AVATAR_INFO					=	1 + SIZE_OF_AVATAR_INFO;
global.P_CREATE_MOUSE_PASSWORD_RECV		=	13;
global.S_CREATE_MOUSE_PASSWORD_RECV		=	5 + MAX_MOUSE_PASSWORD_LENGTH;
global.P_CHANGE_MOUSE_PASSWORD_RECV		=	14;
global.S_CHANGE_MOUSE_PASSWORD_RECV		=	5 + MAX_MOUSE_PASSWORD_LENGTH;
global.P_LOGIN_MOUSE_PASSWORD_RECV		=	15;
global.S_LOGIN_MOUSE_PASSWORD_RECV		=	5;
global.P_CREATE_AVATAR_RECV				=	17
global.S_CREATE_AVATAR_RECV				=	5 + SIZE_OF_AVATAR_INFO;
global.P_DELETE_AVATAR_RECV				=	18;
global.S_DELETE_AVATAR_RECV				=	5;
global.P_RECOMMAND_WORLD_SEND				=	24;
global.S_RECOMMAND_WORLD_SEND				=	13;

module.exports = global;