this.VERSION = 90359;
this.WORKER_SIZE = 256;

this.LOGIN_IP = '127.0.0.1';
this.MY_HOST = '127.0.0.1';
this.MY_USER = 'root';
this.MY_PASS = 'dos';
this.MY_DB = 'game';
this.MY_TB01 = 'DefineMaxUerNum';
this.MY_TB02 = 'MemberInfo';
this.MY_TB03 = 'AvatarInfo';

this.MAX_USER_ID_LENGTH = 101;
this.MAX_USER_PASSWORD_LENGTH = 101;
this.MAX_MOUSE_PASSWORD_LENGTH = 5;

//CLIENT -> LOGIN;
this.P_LOGIN_SEND = 11 ;
this.S_LOGIN_SEND = 13 + this.MAX_USER_ID_LENGTH + this.MAX_USER_PASSWORD_LENGTH;
this.P_CLIENT_OK_FOR_LOGIN_SEND = 12 ;
this.S_CLIENT_OK_FOR_LOGIN_SEND = 9;
this.P_CREATE_MOUSE_PASSWORD_SEND = 13;
this.S_CREATE_MOUSE_PASSWORD_SEND = 9 + this.MAX_MOUSE_PASSWORD_LENGTH;
this.P_CHANGE_MOUSE_PASSWORD_SEND = 14;
this.S_CHANGE_MOUSE_PASSWORD_SEND = 9 + this.MAX_MOUSE_PASSWORD_LENGTH + this.MAX_MOUSE_PASSWORD_LENGTH;
this.P_LOGIN_MOUSE_PASSWORD_SEND = 15;
this.S_LOGIN_MOUSE_PASSWORD_SEND = 9 + this.MAX_MOUSE_PASSWORD_LENGTH;

//LOGIN -> CLIENT;
this.P_LOGIN_RECV = 11 ;
this.S_LOGIN_RECV = 339;
this.P_USER_AVATAR_INFO = 12;
this.S_USER_AVATAR_INFO = 7897;
this.P_CREATE_MOUSE_PASSWORD_RECV = 13;
this.S_CREATE_MOUSE_PASSWORD_RECV = 5 + this.MAX_MOUSE_PASSWORD_LENGTH;
this.P_CHANGE_MOUSE_PASSWORD_RECV = 14;
this.S_CHANGE_MOUSE_PASSWORD_RECV = 5 + this.MAX_MOUSE_PASSWORD_LENGTH;;
this.P_LOGIN_MOUSE_PASSWORD_RECV = 15;
this.S_LOGIN_MOUSE_PASSWORD_RECV = 5;
this.P_RECOMMAND_WORLD_SEND = 24;
this.S_RECOMMAND_WORLD_SEND = 13


module.exports = this;
